name: card_scanner_mine
description: Credit card scanner for Flutter.
version: 1.0.3
homepage: https://example-pet-store.com/newtify

environment:
  sdk: '>=2.14.4 <4.0.0'
  flutter: ">=2.5.3"

dependencies:
  change: ^0.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
 plugin:
    platforms:
      android:
        package: com.nateshmbhat.card_scanner
        pluginClass: CardScannerPlugin
      ios:
        pluginClass: CardScannerPlugin

assets:
    - assets/CHANGELOG.md

